### ISSUE TITLE
Trying to run the bot, but nothing happens

### ISSUE THREAD

**Issue by vivandoshi08** [scaljeri/chess.com#12]
I run the commands like you said and added my credentials, but no new chrome browser or anything even happens.
How do i fix this?

**Comment by vivandoshi08** [comment]
i figured out the issue that i was using linux not mac, but there is still another issue. 
The injected display at the bottom left doesnt come up

**Comment by scaljeri** [comment]
I just had a quick look and I think chess.com changed the way to login, meaning the routing has to be updated

**Comment by vivandoshi08** [comment]
It is fine. I have fixed the issue by fixing the login.
Thanks for responding and helping me though.

**Comment by scaljeri** [comment]
Feel free to create a PR :)
