### ISSUE TITLE
Build fails on windows

### ISSUE THREAD

**Issue by arthur-parmentier** [scaljeri/chess.com#13]
Hi,

On windows I get 

`lerna run build
info cli using local version of lerna
lerna notice cli v3.13.4
lerna info versioning independent
lerna info Executing command in 3 packages: "yarn run build"
lerna ERR! yarn run build exited 1 in '@scaljeri/chess-shared'
lerna ERR! yarn run build stdout:
yarn run v1.22.5
$ rm -rf ./dist && tsc
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
'rm' n'est pas reconnu en tant que commande interne
ou externe, un programme ex�cutable ou un fichier de commandes.
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in '@scaljeri/chess-shared'`

when building the project. The rm command is not recognized. What could I do to fix this?

**Comment by scaljeri** [comment]
Initially that directory doesn't exist anyway, so you could try to remove that task from the package.json files. Otherwise you have to use an npm pakcage to remove that directory. If you have that, I would like to add that (PR would be nice :)

**Comment by arthur-parmentier** [comment]
Hi, after removing the rm commands, this is what I get:

C:\Users\dell\Desktop\chess.com>lerna run build
info cli using local version of lerna
lerna notice cli v3.13.4
lerna info versioning independent
lerna info Executing command in 2 packages: "yarn run build"
lerna ERR! yarn run build exited 1 in '@scaljeri/chess-com-bot'
lerna ERR! yarn run build stdout:
yarn run v1.22.5
$ yarn build:frontend && yarn build:backend && yarn copy-api-worker
$ di -d -c tsc -b ./src -i shared frontend/main.ts -- -p tsconfig-frontend.json && yarn build:browserify
Glob file search: src\**\*.ts
Adding src/shared/environments/komodo.ts
Adding src/shared/game-play.ts
Adding src/shared/turn-observer.ts
Output written to src\frontend\main-di.ts
Running: tsc -p tsconfig-frontend.json
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: spawn tsc ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn tsc',
  path: 'tsc',
  spawnargs: [ '-p', 'tsconfig-frontend.json' ]
}
error Command failed with exit code 1.
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in '@scaljeri/chess-com-bot'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.

**Comment by scaljeri** [comment]
If you google on that error I get the feeling it might be related to how I used spawn. You could for example, try to run the `engine` manually. Go to ./packages/enignes and run `yarn run:sf` for example. The script that it executes now used `spawn`

**Comment by scaljeri** [comment]
I've updated the project, chess.com was completely rewritten so I needed to change some part. It will probably not fix your issues but maybe you have solved them already? If not, did you try Windows Subsystem for Linux (WSL)?
