### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by Kainatic** [scaljeri/chess.com#3]
Hey, I want to test your bot but I'm not able to understand how to install it. Could you simplify the process for me please? I'm not much familiar with using version control. I don't understand yarn and other commands.

Basically, I have downloaded the .zip file. Now what?
(Or now I have downloaded Github Desktop and Cloned it there. Now what?)

I'm on Windows 10 64-bit.

**Comment by scaljeri** [comment]
Hi Kainatic, I've never ran this tool on windows, so I'm not sure if that will work. Furthermore, this is not a tool that you just download and run, you need to have yarn/npm and build it yourself. The READMEs should explain what to do
