### ISSUE TITLE
error TS2304: Cannot find name 'WrapWithPromise'

### ISSUE THREAD

**Issue by juntangnj** [scaljeri/chess.com#30]
After I configure the ./packages/bot/src/frontend/environment.ts by comment out the two lines below //Pure browser engine and uncomment the single line below //Pure backend engine and then run the command: lerna run build, I got the following errors:

Task skipped, content unchanged (src/backend/main-di.ts)
Running: tsc -p tsconfig-backend.json
../../node_modules/webdriverio/webdriverio.d.ts(18,34): error TS2304: Cannot find name 'WrapWithPromise'.

../../node_modules/webdriverio/webdriverio.d.ts(29,34): error TS2304: Cannot find name 'WrapWithPromise'.

$ cp ./src/backend/worker-import.js ./dist/
Done in 14.70s.
lerna success run Ran npm script 'build' in 3 packages in 18.5s:
lerna success - @scaljeri/chess-com-bot
lerna success - @scaljeri/chess-engine
lerna success - @scaljeri/chess-shared

It looks like the build is declared success even with those errors in the middle. However, I could not run it. The command: lerna run start give some errors but not sure if they are related to the earlier errors in the build command:

juntang@Juns-Mac chess.com-master % lerna run start
info cli using local version of lerna
lerna notice cli v3.13.4
lerna info versioning independent
lerna info Executing command in 3 packages: "yarn run start"
lerna ERR! yarn run start exited 1 in 'statistics'
lerna ERR! yarn run start stdout:
yarn run v1.22.15
$ rm -r ./dist && tsc && cp ./src/index.html ./dist && browserify ./dist/www/main.js -o ./dist/www/main.js && ts-node ./src/server.ts
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run start stderr:
rm: ./dist: No such file or directory
error Command failed with exit code 1.

lerna ERR! yarn run start exited 1 in 'statistics'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.

**Comment by mccallw23** [comment]
I ran into this as well.

**Comment by scaljeri** [comment]
Yes, the project has some issues and isn't very stable anymore. The web version of Stockfish has issues as well unfortunately.  If you run the pure Docker/backend version you might have more luck. If you go to `packages/engine` and run `npm run run:sf` it should spin up fine (if you have docker running of course). Then in the `packages/bot` run `npm start` it might work (make sure to modify the bot config file to make sure it doesn't use the web assembly engine!)

But this project is unstable right now and needs to be fixed.  But I don't have much time right now, sorry, so it might take some time before I can do it. Sorry for that, but feel free to look in to the code of course :)

**Comment by scaljeri** [comment]
I think its fixed
