### ISSUE TITLE
Running Commands but no bot on chess.com

### ISSUE THREAD

**Issue by mrnighttime** [scaljeri/chess.com#5]
$> git clone https://github.com/scaljeri/chess.com
$> cd chess.com
$> yarn
$> lerna run build

Updated ./packages/bot/.env as follows
USERNAME=April302020
PASSWORD=xxxxxxxx

and began a game on chess.com to no avail

**Comment by scaljeri** [comment]
It seems that they blocked my IP and accounts completely, I need some time to setup VPN .

Can you confirm that the app does log you in?
Do you see any errors in the console?

**Comment by scaljeri** [comment]
I've pushed an update, they changed the classes in the HTML for the login submit button. If you pull master, build again and run it, you should now be able to automatically login and see the small dashboard at the bottom left corner. If you start a game it should automatically take over

**Comment by busybox11** [comment]
Hey,
So, I've got a similar problem. I edited the `client.ts` file to use the linux path for chrome. The browser starts fine but it closes itself after some time. It seems that it can't login. See attached screenshot.
![image](https://user-images.githubusercontent.com/29630035/102629928-23ddf200-414c-11eb-88be-8e5a4839dbf6.png)
I tried to edit the file but I don't understand that much what you did so I rely on this issue. HopI hope you'll be able to help me.
Keep up the good work and thanks for this awesome tool :)

**Comment by scaljeri** [comment]
I just checked chess.com and the site has completely changed. I think they completely rewrote it with Svelte. Anyway, it seems that you can play now against an engine without login, which is nice.  I removed the login, but all the class selectors I use right now are invalid now (they changed everything). If you checkout my last commit you can basically see where those thing are located in the code. Feel free to help :)

**Comment by busybox11** [comment]
Okay, thank you!
I think I'm going to look forward into contributing to this amazing project. This will be my first experience in typescript tho, don't expect anything "good" haha.
Thanks a lot again! :)

**Comment by scaljeri** [comment]
That would be great :) Did you see the article I wrote about this project: https://medium.com/swlh/programming-a-chess-bot-for-chess-com-fa6bd7e1da76 ?

**Comment by busybox11** [comment]
Yes I did! That's how I found this project, in fact.

**Comment by scaljeri** [comment]
Ah ok, thats nice!

Right now, the client-side seems to be working again up to the point where it needs to move a piece. I guess they changed the logic of how to make the move. So [this](https://github.com/scaljeri/chess.com/blob/master/packages/bot/src/frontend/contexts/live/utils/mover.ts) logic doesn't do the trick anymore.

**Comment by busybox11** [comment]
Huh. So a reimplementation of this part is needed, right?

**Comment by scaljeri** [comment]
Yes, its this

![image](https://user-images.githubusercontent.com/1078741/102701079-908fe400-4253-11eb-83ab-5fc31b795c3b.png)

this is the key part.

**Comment by scaljeri** [comment]
It was easy :) They changed to pointer events :) It now makes the initial move

**Comment by busybox11** [comment]
Oh, nice!
I'm going to test this asap then.
Thanks a lot for your help! (Even though I did not do anything, sorry...)

**Comment by scaljeri** [comment]
I fixed it. If you start it, it should all boot up nicely, just wait until you see the injected display. Then you can hit 'play' (no docker required). Right now it uses the web-assembly stockfish version. Chess.com also uses an in-browser chess engine, which is not very strong
